Repository LeonIvovic/PI-Projekt, pull requests merged in 2023-04, with the labels that each got.

#29 Game manager
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Player.prefab.meta
  Assets/Scenes/Level 1.unity
  Assets/Scenes/Level 2.unity
  Assets/Scripts/GameManager.cs
  Assets/Scripts/GameManager.cs.meta
  Assets/Scripts/NextLevelLoader.cs
  Assets/Scripts/NextLevelLoader.cs.meta
  Assets/Scripts/PlayerController.cs
  Assets/Scripts/Singleton.cs
  Assets/Scripts/Singleton.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectVersion.txt
  UserSettings/Layouts/default-2021.dwlt
Labels: gameplay, feature

#28 Ma level2 platfroms
  .gitignore
  Assets/PlayerMovementData.asset
  Assets/Prefabs/Level2.meta
  Assets/Prefabs/Level2/Ground1.prefab
  Assets/Prefabs/Level2/Ground1.prefab.meta
  Assets/Prefabs/Level2/Ground2.prefab
  Assets/Prefabs/Level2/Ground2.prefab.meta
  Assets/Prefabs/Level2/Ground3.prefab
  Assets/Prefabs/Level2/Ground3.prefab.meta
  Assets/Prefabs/Level2/Spike.prefab
  Assets/Prefabs/Level2/Spike.prefab.meta
  Assets/Prefabs/Level2/SpikeGround.prefab
  Assets/Prefabs/Level2/SpikeGround.prefab.meta
  Assets/Prefabs/Main terrain.meta
  Assets/Prefabs/Main terrain/CM Boundaries.prefab
  Assets/Prefabs/Main terrain/CM Boundaries.prefab.meta
  Assets/Prefabs/Main terrain/EndPlatform.prefab
  Assets/Prefabs/Main terrain/EndPlatform.prefab.meta
  Assets/Prefabs/Main terrain/StartPlatform.prefab
  Assets/Prefabs/Main terrain/StartPlatform.prefab.meta
  Assets/Prefabs/Player.prefab
  Assets/Scenes/Level 1.unity
  Assets/Scenes/Level 2.unity
  Assets/Scripts/GroundSpawner.cs
  Assets/Scripts/LevelElement.cs
  Assets/Scripts/LevelGenerator.cs
  Assets/Scripts/OnContactDamage.cs
  Assets/Scripts/OnContactDamage.cs.meta
  Assets/Scripts/PlayerController.cs
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/CurrentMaximizeLayout.dwlt
  UserSettings/Layouts/default-2021.dwlt
Labels: level design

#41 Dodan README.md temeljni opis
  README.md
Labels: documentation

#44 Ispravci levela 2
  Assets/Prefabs/Main terrain/EndPlatform.prefab
  Assets/Scripts/LevelGenerator.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: bug

#48 Dodan novi sprite glavnog lika
  Assets/Prefabs/Level2/Spike.prefab
  Assets/Prefabs/Player.prefab
  Assets/Scenes/Level 1.unity
  Assets/Scenes/Level 2.unity
  Assets/Sprites/Character/playerchar1.png.meta
  ProjectSettings/ProjectVersion.txt
  UserSettings/EditorUserSettings.asset
Labels: art, player
